# ZhiPuAiChatClientController类的simpleChat方法
GET http://localhost:10003/zhipuai/chat-client/simple/chat

###
# ZhiPuAiChatClientController类的streamChat方法
GET http://localhost:10003/zhipuai/chat-client/stream/chat

###
# ZhiPuAiChatModelController类的simpleChat方法
GET http://localhost:10003/zhipuai/chat-model/simple/chat

###
# ZhiPuAiChatModelController类的streamChat方法
GET http://localhost:10003/zhipuai/chat-model/stream/chat

###
# ZhiPuAiChatModelController类的customChat方法
GET http://localhost:10003/zhipuai/chat-model/custom/chat
