# AzureOpenAiChatModelController类的simpleChat方法
GET http://localhost:10009/azure/openai/chat-model/simple/chat

###
# AzureOpenAiChatModelController类的streamChat方法
GET http://localhost:10009/azure/openai/chat-model/stream/chat

###
# AzureOpenAiChatModelController类的clientChat方法
GET http://localhost:10009/azure/openai/chat-client/chat

###
# AzureOpenAiChatModelController类的clientStreamChat方法
GET http://localhost:10009/azure/openai/client/stream/chat
