# VllmChatModelController类的simpleChat方法
GET http://localhost:10003/vllm/chat-model/simple/chat

###
# VllmChatModelController类的streamChat方法
GET http://localhost:10003/vllm/chat-model/stream/chat

###
# VllmChatModelController类的customChat方法
GET http://localhost:10003/vllm/chat-model/custom/chat
