# OllamaChatModelController类的simpleChat方法
GET http://localhost:10005/model/simple/chat

###
# OllamaChatModelController类的streamChat方法
GET http://localhost:10005/model/stream/chat

###
# OllamaChatModelController类的customChat方法
GET http://localhost:10005/model/custom/chat

###
# OllamaChatClientController类的simpleChat方法
GET http://localhost:10005/client/simple/chat

###
# OllamaChatClientController类的streamChat方法
GET http://localhost:10005/client/stream/chat
