# OpenAiChatClientController类的simpleChat方法
GET http://localhost:10003/openai/chat-client/simple/chat

###
# OpenAiChatClientController类的streamChat方法
GET http://localhost:10003/openai/chat-client/stream/chat

###
# OpenAiChatModelController类的simpleChat方法
GET http://localhost:10003/openai/chat-model/simple/chat

###
# OpenAiChatModelController类的streamChat方法
GET http://localhost:10003/openai/chat-model/stream/chat

###
# OpenAiChatModelController类的customChat方法
GET http://localhost:10003/openai/chat-model/custom/chat

###
# OpenAiChatModelController类的jsonChat方法
GET http://localhost:10003/openai/chat-model/custom/chat/json-mode
