# DashScopeChatClientController类的simpleChat方法
GET http://localhost:10000/client/simple/chat

###
# DashScopeChatClientController类的streamChat方法
GET http://localhost:10000/client/stream/chat

###
# DashScopeChatClientController类的analyzeImageByUrl方法
GET http://localhost:10000/client/image/analyze/url

###
# DashScopeChatClientController类的analyzeImageByUpload方法
POST http://localhost:10000/client/image/analyze/upload

###
# DashScopeChatModelController类的simpleChat方法
GET http://localhost:10000/model/simple/chat

###
# DashScopeChatModelController类的streamChat方法
GET http://localhost:10000/model/stream/chat

###
# DashScopeChatModelController类的tokens方法
GET http://localhost:10000/model/tokens

###
# DashScopeChatModelController类的customChat方法
GET http://localhost:10000/model/custom/chat

###
# DashScopeChatModelController类的dashScopeWebSearch方法
GET http://localhost:10000/model/dashscope/web-search

###
# DashScopeChatModelController类的dashScopeWebSearch2方法
GET http://localhost:10000/model/dashscope/web-search/2

###
# DashScopeChatModelController类的customHttpHeaders方法
GET http://localhost:10000/model/custom/http-headers

###
GET http://localhost:10000/model/search/info/streams
